"use client";

import { useState } from "react";
import Sidebar from "@/components/Sidebar";

import {
  BarChart3,
  CalendarDays,
  Download,
  FileText,
  Hospital,
  TrendingUp,
} from "lucide-react";

type Report = {
  id: number;
  title: string;
  period: string;
  type: string;
  generated: string;
  status: string;
};

const initialReports: Report[] = [
  {
    id: 1,
    title: "District PHC Priority Ranking Report",
    period: "August 2026",
    type: "Priority Assessment",
    generated: "02 August 2026",
    status: "Ready",
  },
  {
    id: 2,
    title: "Critical PHC Intervention Report",
    period: "August 2026",
    type: "Emergency Action",
    generated: "02 August 2026",
    status: "Ready",
  },
  {
    id: 3,
    title: "Patient Load Analysis Report",
    period: "Last 7 Days",
    type: "Analytics",
    generated: "01 August 2026",
    status: "Ready",
  },
  {
    id: 4,
    title: "Infrastructure Readiness Report",
    period: "July 2026",
    type: "Infrastructure",
    generated: "31 July 2026",
    status: "Ready",
  },
  {
    id: 5,
    title: "PHC Staffing Availability Report",
    period: "July 2026",
    type: "Workforce",
    generated: "30 July 2026",
    status: "Ready",
  },
];

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>(initialReports);

  const [reportType, setReportType] = useState(
    "PHC Priority Ranking"
  );

  const [region, setRegion] = useState("All Regions");

  const [fromDate, setFromDate] = useState("");

  const [toDate, setToDate] = useState("");

  const [message, setMessage] = useState("");

  function getTodayDate() {
    return new Date().toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });
  }

  function generateReport() {
    if (!fromDate || !toDate) {
      setMessage(
        "Please select both the From Date and To Date."
      );
      return;
    }

    if (new Date(fromDate) > new Date(toDate)) {
      setMessage(
        "The From Date cannot be later than the To Date."
      );
      return;
    }

    const newReport: Report = {
      id: Date.now(),
      title: `${reportType} Report`,
      period: `${fromDate} to ${toDate}`,
      type: reportType,
      generated: getTodayDate(),
      status: "Ready",
    };

    setReports((currentReports) => [
      newReport,
      ...currentReports,
    ]);

    setMessage(
      `${reportType} report was generated successfully for ${region}.`
    );
  }

  function downloadReport(report: Report) {
    const reportHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">

<title>${report.title}</title>

<style>
body {
  font-family: Arial, sans-serif;
  margin: 50px;
  color: #0f172a;
}

.header {
  border-bottom: 4px solid #1d4ed8;
  padding-bottom: 20px;
}

h1 {
  color: #1e40af;
}

.subtitle {
  color: #64748b;
}

.info {
  margin-top: 30px;
  border-collapse: collapse;
  width: 100%;
}

.info td {
  border: 1px solid #cbd5e1;
  padding: 14px;
}

.label {
  font-weight: bold;
  background: #eff6ff;
  width: 30%;
}

.summary {
  margin-top: 30px;
  padding: 20px;
  background: #f8fafc;
  border-left: 5px solid #2563eb;
}

.footer {
  margin-top: 50px;
  color: #64748b;
  font-size: 13px;
}
</style>
</head>

<body>

<div class="header">
<h1>AarogyaRank</h1>

<p class="subtitle">
PHC Priority Ranking System
</p>
</div>

<h2>${report.title}</h2>

<table class="info">

<tr>
<td class="label">Report Type</td>
<td>${report.type}</td>
</tr>

<tr>
<td class="label">Assessment Period</td>
<td>${report.period}</td>
</tr>

<tr>
<td class="label">Generated Date</td>
<td>${report.generated}</td>
</tr>

<tr>
<td class="label">Status</td>
<td>${report.status}</td>
</tr>

</table>

<div class="summary">

<h3>Assessment Summary</h3>

<p>
This report was generated by the AarogyaRank PHC Priority
Ranking System. It contains district-level healthcare
assessment information based on infrastructure,
staffing, patient utilization, and population needs.
</p>

<p>
The current system monitors 10 Primary Health Centres
and identifies facilities requiring urgent intervention.
</p>

</div>

<div class="footer">

Generated by AarogyaRank • PHC Priority Ranking System

</div>

</body>
</html>
`;

    const blob = new Blob([reportHtml], {
      type: "text/html",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download =
      report.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "") +
      ".html";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">

      <Sidebar />

      <main className="min-h-screen p-6 lg:ml-64 lg:p-10">

        {/* Page heading */}

        <div className="mb-8">

          <p className="text-sm font-medium text-slate-500">
            Home / Reports
          </p>

          <h1 className="mt-2 text-3xl font-bold">
            Reports & Export Center
          </h1>

          <p className="mt-2 text-slate-500">
            Generate and download district-level PHC
            assessment reports.
          </p>

        </div>

        {/* Summary cards */}

        <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>

                <p className="text-sm text-slate-500">
                  Total Reports
                </p>

                <h2 className="mt-2 text-3xl font-bold">
                  {reports.length + 19}
                </h2>

              </div>

              <div className="rounded-xl bg-blue-50 p-3 text-blue-700">

                <FileText size={25} />

              </div>

            </div>

            <p className="mt-4 text-xs text-emerald-700">
              Reports available for download
            </p>

          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>

                <p className="text-sm text-slate-500">
                  PHCs Covered
                </p>

                <h2 className="mt-2 text-3xl font-bold">
                  10
                </h2>

              </div>

              <div className="rounded-xl bg-emerald-50 p-3 text-emerald-700">

                <Hospital size={25} />

              </div>

            </div>

            <p className="mt-4 text-xs text-slate-500">
              All monitored PHCs included
            </p>

          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>

                <p className="text-sm text-slate-500">
                  Latest Assessment
                </p>

                <h2 className="mt-2 text-3xl font-bold">
                  Today
                </h2>

              </div>

              <div className="rounded-xl bg-violet-50 p-3 text-violet-700">

                <CalendarDays size={25} />

              </div>

            </div>

            <p className="mt-4 text-xs text-slate-500">
              Latest system assessment
            </p>

          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">

            <div className="flex items-center justify-between">

              <div>

                <p className="text-sm text-slate-500">
                  Critical PHCs
                </p>

                <h2 className="mt-2 text-3xl font-bold text-red-600">
                  2
                </h2>

              </div>

              <div className="rounded-xl bg-red-50 p-3 text-red-600">

                <TrendingUp size={25} />

              </div>

            </div>

            <p className="mt-4 text-xs text-red-600">
              Immediate action required
            </p>

          </div>

        </section>

        {/* Generate report form */}

        <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

          <div className="flex items-center gap-3">

            <div className="rounded-xl bg-blue-50 p-3 text-blue-700">

              <BarChart3 size={24} />

            </div>

            <div>

              <h2 className="text-xl font-bold">
                Generate New Report
              </h2>

              <p className="text-sm text-slate-500">
                Select a report type and assessment range.
              </p>

            </div>

          </div>

          <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4">

            <div>

              <label className="mb-2 block text-sm font-semibold">
                Report Type
              </label>

              <select
                value={reportType}
                onChange={(event) =>
                  setReportType(event.target.value)
                }
                className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"
              >

                <option>
                  PHC Priority Ranking
                </option>

                <option>
                  Infrastructure Readiness
                </option>

                <option>
                  Patient Load Analysis
                </option>

                <option>
                  Staffing Availability
                </option>

              </select>

            </div>

            <div>

              <label className="mb-2 block text-sm font-semibold">
                PHC Region
              </label>

              <select
                value={region}
                onChange={(event) =>
                  setRegion(event.target.value)
                }
                className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3"
              >

                <option>
                  All Regions
                </option>

                <option>
                  Puducherry
                </option>

                <option>
                  Bahour
                </option>

                <option>
                  Karaikal
                </option>

                <option>
                  Villianur
                </option>

              </select>

            </div>

            <div>

              <label className="mb-2 block text-sm font-semibold">
                From Date
              </label>

              <input
                type="date"
                value={fromDate}
                onChange={(event) =>
                  setFromDate(event.target.value)
                }
                className="w-full rounded-xl border border-slate-300 px-4 py-3"
              />

            </div>

            <div>

              <label className="mb-2 block text-sm font-semibold">
                To Date
              </label>

              <input
                type="date"
                value={toDate}
                onChange={(event) =>
                  setToDate(event.target.value)
                }
                className="w-full rounded-xl border border-slate-300 px-4 py-3"
              />

            </div>

          </div>

          <button
            onClick={generateReport}
            className="mt-6 flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white transition hover:bg-blue-800"
          >

            <FileText size={18} />

            Generate Report

          </button>

          {message && (

            <div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm font-medium text-blue-800">

              {message}

            </div>

          )}

        </section>

        {/* Generated reports */}

        <section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">

          <div className="border-b border-slate-200 p-6">

            <h2 className="text-xl font-bold">
              Generated Reports
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Download available PHC assessment reports.
            </p>

          </div>

          <div className="overflow-x-auto">

            <table className="w-full min-w-[850px] text-left">

              <thead className="bg-slate-50">

                <tr>

                  <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">
                    Report
                  </th>

                  <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">
                    Period
                  </th>

                  <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">
                    Type
                  </th>

                  <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">
                    Generated
                  </th>

                  <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">
                    Status
                  </th>

                  <th className="px-6 py-4 text-center text-xs font-bold uppercase text-slate-500">
                    Action
                  </th>

                </tr>

              </thead>

              <tbody>

                {reports.map((report) => (

                  <tr
                    key={report.id}
                    className="border-t border-slate-100 hover:bg-slate-50"
                  >

                    <td className="px-6 py-5">

                      <p className="font-semibold">
                        {report.title}
                      </p>

                      <p className="mt-1 text-xs text-slate-500">
                        AarogyaRank District Administration
                      </p>

                    </td>

                    <td className="px-6 py-5 text-sm text-slate-600">

                      {report.period}

                    </td>

                    <td className="px-6 py-5">

                      <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">

                        {report.type}

                      </span>

                    </td>

                    <td className="px-6 py-5 text-sm text-slate-600">

                      {report.generated}

                    </td>

                    <td className="px-6 py-5">

                      <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">

                        {report.status}

                      </span>

                    </td>

                    <td className="px-6 py-5 text-center">

                      <button
                        onClick={() =>
                          downloadReport(report)
                        }
                        className="inline-flex items-center gap-2 rounded-lg border border-blue-700 px-4 py-2 text-xs font-semibold text-blue-700 transition hover:bg-blue-700 hover:text-white"
                      >

                        <Download size={15} />

                        Download

                      </button>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        </section>

      </main>

    </div>
  );
}